version: '3.8'

services:
  api-sentinel:
    build: .
    container_name: api-sentinel-bot
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    shm_size: '2gb'
